[project]
name = "bib-tui"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bibtexparser>=2.0.0b9",
    "habanero>=2.3.0",
    "textual>=8.0.0",
    "textual-dev>=1.8.0",
]
